version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # モデルファイルをマウント（存在する場合）
      - ./wiki_nouns_only.model:/src/wiki_nouns_only.model
    environment:
      - PYTHONPATH=/src
    restart: unless-stopped 